# Generated by Django 3.2 on 2021-04-25 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_email', models.EmailField(max_length=254)),
                ('repeat_email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=1024)),
                ('message', models.TextField(max_length=2048)),
            ],
        ),
    ]
